### ISSUE TITLE
Wrong import of `utils`

### ISSUE THREAD

**Issue by Kalabasa** [Kelin2025/vue-timers#13]
In mixin.js

```
export 'utils' was not found in './utils'
```

**Comment by andythekid** [comment]
Same problem.
Strange, that in mixin.js we have:
> import { utils } from './utils'

and in utils.js:

> export default util

**Comment by Kalabasa** [comment]
I see. Seems simple. This PR should fix it, right?

**Comment by andythekid** [comment]
I think u must also rename variable from 'util' to 'utils' and change 'export default util' in utils.js
