### ISSUE TITLE
cannot change .time property (typo?)

### ISSUE THREAD

**Issue by tomi20v** [Kelin2025/vue-timers#17]
my usecase: I set a default value for 'time' but before starting the timer I want to change it (the value to use comes from an API)
however, due to a typo in mixin.js it will always use the default value.
my code:
```
    timers: {
      settings: {
        callback: ...,
        autostart: false,
        repeat: true,
        immediate: false,
        time: 60*1000,
      }
    },
```
then, in the component's created() I do something like:
```
            this.timers.settings.time = 5 * 1000;
            this.$timer.start('settings');
```
(instead of 5 I'm using a dynamic value)

as I see, the problem comes from a typo in mixin.js, line #97:
```
        data[name].instance = generateTimer(
          set('timer', data[name].time, options[name]),
          vm
        )
```
if I change it to
```
set('time', data[name].time, options[name]),
```
it works as expected.

**Comment by Kelin2025** [comment]
Fixed in `1.7.2`. Sorry for delay
