### ISSUE TITLE
Use factory function to allow access to vm

### ISSUE THREAD

**Issue by dodas** [Kelin2025/vue-timers#20]
Hi, thanks for this mixin!
I've got one little issue with it:

it would be nice nice to be able to pass factory function to "timers" options object, which would have access to vue instance, so I can, for example, use data from props to set `time` property of timer.

Example:
```js
timers: {
  visibilityTimer() {
    return {
      autostart: false,
      callback() {
        // ...
      },
      time: this.timeout, // <- I am not able to do this now.
    }
  },
},
```

What do you think? Should I do an PR?

**Comment by Kelin2025** [comment]
There are some questions
- What if `time` is changed during already started timer?
- The same question about intervals
- Maybe add smth like `timeProp` or string value for `time`?

**Comment by Kelin2025** [comment]
Closed due to inactivity
