### ISSUE TITLE
【new feature】compress the code for the limit-size 

### ISSUE THREAD

**Issue by masongzhi** [Kelin2025/vue-timers#25]
I saw the limit-size package in project, would it compress when vue webpack build ? If not I wish it can compress the code

**Comment by Kelin2025** [comment]
size-limit only checks bundle size. It doesn't compress anything
- Would it compress when vue webpack build?
- Depends on your webpack config I guess

**Comment by masongzhi** [comment]
ok, then I know how to compress this package with webpack in project
