### ISSUE TITLE
Attempts to remove $timer's methods

### ISSUE THREAD

**Issue by fer22f** [Kelin2025/vue-timers#3]
This errors clutters the screen on route change: `Error in beforeDestroy hook: "TypeError: timers[name] is undefined"`

And this is due to this:
https://github.com/Kelin2025/vue-timers/blob/dfb19a44ca63f36abdc285b5f6103832a43a37fd/mixin.js#L140-L142

`this.$timers` contains some methods such as `add` and it fails when iterating through those, because they aren't actual timers.

**Comment by Kelin2025** [comment]
Have some problems on my work. I will fix all issues on weekends.

**Comment by fer22f** [comment]
No problems, I would suggest running a linter, would highlight 50% of the problems

**Comment by Kelin2025** [comment]
I reworked plugin _from scratch_. Looks like it's fine now :)  
Please leave a comment if some of your issues are still relevant
