### ISSUE TITLE
Combine Timer with Mouse Idle

### ISSUE THREAD

**Issue by BennieBe** [Kelin2025/vue-timers#30]
It would be a good addition to the timer to allow for checking if mouse has been idle for a specific amount of time before the timer starts.

**Comment by Blanen** [comment]
@BennieBe 

`window.addEventListener('mousemove',this.mouseIsMoving);`

then reset the timer in the mouseIsMoving function.

**Comment by Kelin2025** [comment]
I don't see any sense in implementing things like this in library. Not all people need such special cases
