### ISSUE TITLE
Fix tests

### ISSUE THREAD

**Issue by Kelin2025** [Kelin2025/vue-timers#34]
After updating babel, tests fail with the weird error ![image](https://user-images.githubusercontent.com/4208480/55878867-06e6d280-5ba6-11e9-93c3-d9a308559c74.png)
According to babel docs, `targets` option is valid 
![image](https://user-images.githubusercontent.com/4208480/55879259-d9e6ef80-5ba6-11e9-9b11-a3f10609e77a.png)

🤔

**Comment by Kelin2025** [comment]
cc @masongzhi

**Comment by masongzhi** [comment]
this is my fault, I take the ":" into the key https://github.com/Kelin2025/vue-timers/pull/35
