### ISSUE TITLE
there is no index.min.js in npm package

### ISSUE THREAD

**Issue by masongzhi** [Kelin2025/vue-timers#36]
![image](https://user-images.githubusercontent.com/19945145/56105044-061abb80-5f6d-11e9-9543-6ab248317801.png)
it only has `index.js`, is this because of this problem?
![image](https://user-images.githubusercontent.com/19945145/56105102-45490c80-5f6d-11e9-83e7-14943cffbb8e.png)
@Kelin2025

**Comment by Kelin2025** [comment]
Meh, forgot to build before packaging the app. Fixed in `2.0.2`
