### ISSUE TITLE
browser support

### ISSUE THREAD

**Issue by Andrei-Pozolotin** [Kelin2025/vue-timers#49]
1. to work in bare browser (no import, no webpack) most vue plugins provide umd dist, i.e.:
https://github.com/vuejs/vue-router/blob/dev/dist/vue-router.js
https://github.com/LinusBorg/portal-vue/blob/develop/dist/portal-vue.umd.js

2. in order for browser import to work
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import

these:
https://github.com/Kelin2025/vue-timers/blob/master/index.js
```
import VueTimers from './mixin'
```
should use `*.js`
```
import VueTimers from './mixin.js'
```

**Comment by masongzhi** [comment]
you mean it should be build to umd format?

**Comment by Andrei-Pozolotin** [comment]
yes, including umd, please. for tests via jsfiddle, etc.

**Comment by Andrei-Pozolotin** [comment]
thank you
