### ISSUE TITLE
Default for repeat should be documented as false

### ISSUE THREAD

**Issue by fer22f** [Kelin2025/vue-timers#7]
The default for repeat is now false:
https://github.com/Kelin2025/vue-timers/blob/ebe8fa3a2ed489456a0c5eec8dc4a9982fa0b1c3/mixin.js#L53

While the documentation doesn't reflect that:
https://github.com/Kelin2025/vue-timers/blob/ebe8fa3a2ed489456a0c5eec8dc4a9982fa0b1c3/README.md#L89-L91

**Comment by Kelin2025** [comment]
Yep! Thank you :) 
https://github.com/Kelin2025/vue-timers/commit/f9a677f60cb2dda758aa5a83cc882f4720a1c4e7#diff-04c6e90faac2675aa89e2176d2eec7d8L90
