### ISSUE TITLE
Feature Request: Stop timers based on inViewport

### ISSUE THREAD

**Issue by timrijkse** [Kelin2025/vue-timers#8]
Nice work on the automagically removing the timers on beforeDestroy. Another performance win would be to check whether the component is in viewport or not and then disable/enable the timers.

Any thoughts on this? Would love to do a PR :)

**Comment by Kelin2025** [comment]
Hello!
Can you explain what do you mean by _"component is in viewport"_? Checking whether component is _visible_ or not? Or is _rendered_?

**Comment by timrijkse** [comment]
Hey! Indeed. whether it is visible in the screen or not

**Comment by Kelin2025** [comment]
Looks like it's not related to vue-timers  
For now, `vue-timers` remove timers on component destroy.  
And, if component is _hidden_ but alive, it will continue work. I think it's expected behavior, no need to remove timer in this case  
Maybe I didn't understand use case :thinking:
